### PR TITLE
TASK #A2.0 and TASK#3.0

### PR DESCRIPTION
**Pull request by davidsemakula**
Create a front end “widget” that will be populated with the user Info from the DB.
Also, create the YES / NO button to capture the users choice. [Default : YES]

Create a Log In screen which authenticates based on the $id + $password combination.

Fixes: https://github.com/whereAt-Industries/Butterfly.W./issues/2 and https://github.com/whereAt-Industries/Butterfly.W./issues/3

### CODE REVIEW

**Comment by gerardsimons** [comment]
Hi David,

My name is Gerard, I am in the development team of whereAt. We are very happy with your work so far, and wish to continue this issue. 

Next up we need to connect the app to the back-end server. We have created several API functions that you need to call that will return results (GET) and that will allow you to update results (POST).

First, the authentication in this issue:

When you login, you need to authenticate at the server using a POST request and passing an API key, a username and a password, the last two should be fetched from the form, the API key may be hardcoded.

You can use these details to test:

apiKey : ]wv2Np:c@e8V9@>r37g){18u.32lY
username : gsimons
password : swordpass

I have included a screenshot of my Postman screen (a useful plugin for Chrome which you can use to test requests, if you do not have one already)

postman-sub

The details returned in JSON should be used as variables for the next screen #4 

I hope this makes everything clear, let me know if you have any questions

**Comment by davidsemakula** [comment]
Hi @gerardsimons great so far, I have two questions though,

QN 1: Can I go ahead and implement this with a frontend framework like AngularJS?

QN 2: What's the API endpoint for saving the user's choice for alerts after sign in? Or even better a link to some api docs.

**Comment by gerardsimons** [comment]
Hi David,

QN1:  Yes that is great, please do. In fact, we would prefer such a thing for scalability and extensibility reasons. Do you by any chance also have experience with Polymer? If so, that would be even better, as making web components for each task would be very convenient for our dashboard-like layout we have in mind, but this is only if you have experience in this, otherwise AngularJS is also fine.

QN2: Unfortunately, we don't yet have a comprehensive online documentation (working on it), but I will be sure to post a similar API description as the one above to describe how to save the alert preference, ASAP.

**Comment by gerardsimons** [comment]
And here is an example of how to save the preferences to the database. 

URL: http://whereatcloud.com/bletracker/api/v1/settings
Method: POST
Parameters : APIKey, username and password from previous example
alert : boolean (true or false) indicating the new setting for the alert notification

Example:

settings-post

I hope you have all the information you need now to finish the issue as described

**Comment by davidsemakula** [comment]
Hi @gerardsimons 
Went ahead and implemented with Polymer

A few issues:
1. /settings endpoint always returns true (except for case of missing params) and has a typo in the success key (_'succes'_ instead of _'success'_)
   - On an architectural level I think it would be better for this endpoint to return the modified object and communicate success and error through HTTP status codes
2. Profile object returned by /user/login endpoint should contain Company Name instead of (or in addition to) the Company ID
3. No token based authentication (OAuth or JWT) and no CORS 
   - Lack of both means no purely frontend solution
   - No CORS means no AJAX requests directly to API (wouldn't be a problem if API and frontend where same origin, which isn't the case in development, may not be a problem in production).
   - As a solution I implemented a PHP relay to sit between Frontend and API that handles authentication (via sessions) and also relays AJAX requests from the frontend to the API via CURL.This could be removed once this issue is resolved.

Cheers.

**Comment by gerardsimons** [comment]
Hi David,

Great stuff, and especially cool you know how to use Polymer. I will check your work soon. 

For now to adress your points (thank you for the feedback BTW, very valuable), and thank you for noticing the bug. 
1. Indeed you are right that architecturally and in trying to be more truly RESTful, the return object should rather be the modified or newly created object. This is something we want to have, what you are currently working with is just a quick stub, so that we can have a demo running even though the server API is not yet complete.
2. Good catch, I will fix that
3. Unfortunately because we need a small quick demo, authentication has not yet been correctly implemented, but is definitely something we need to before going into production. Nice workaround, thanks for that. Was not aware of the restriction you mentioned so thank you also for that.

I will be back once I completely check the implementation

**Comment by davidsemakula** [comment]
@gerardsimons great

**Comment by gerardsimons** [comment]
Hi David,

Just to let you know, I will check your work this week, I am sorry for the delay, I have been very busy with other things.

**Comment by gerardsimons** [comment]
Hi David,

I had time to look today. I am no Polymer expert, in fact never developed with it myself, so I could not resolve this error quickly, but I think it has to do with paths being declared absolutely (/app/... rather than app/... ). Please see screenshot below:

error copy

Could you fix this and make sure it is able to find paths relative?

**Comment by davidsemakula** [comment]
Hi Gerard,

Just realized that I neglected to update the readme to indicate that you should serve the /app directory from a webserver with php support (like wampserver) for login (and other API calls) to work. I'm guessing you're using `gulp serve`.

I have updated the readme to be a little more clear about this.

**Comment by gerardsimons** [comment]
Hi David,

I was indeed using `gulp serve`. I tried changing my LAMP server's document root to the butterfly/app folder, but this does not seem to work, and even it would work, this would not be preferable. Is there a way to get it running without changing the document root ?

I did manage to get it running by going to localhost/butterfly/app. This seems to work, and it is looking great when it loads, but I notice it does not always load for me. Sometimes the page is blank, this might be because of my workaround, or because the bootstrap.min.css fails to load (but this also happens when it does load)? See error log in screenshot:

3_error tiff

This is when it loads correctly, which is looking fine

2 tiff

I also changed the API so that now the Company_Name is returned, could you change it so that the Company_ID is no longer displayed, but rather the Company_Name?

Other than that is looking as we would like, but it would be great if we could resolve those last issues.

**Comment by davidsemakula** [comment]
Hi Gerard,
Have addressed the issues you raised in the latest commit.

Also added more testing and deployment info in the readme. 
I made some changes to bower config so please be sure to run ```bower install``` again when following the deployment guide.
The updated deployment guide is more inline with what you would typically do to move the polymer app into production.

Serving the ```app``` folder was just a quick way of getting the app running which i thought would work great in development.

**Comment by davidsemakula** [comment]
Hi Gerard,
I've addressed the issues you raised and added more testing and deployment info to the readme. 

Be sure to run `npm install && bower install` again

**Comment by gerardsimons** [comment]
Hi David, 

Great work, everything seems to work flawlessly now. As far as I concerned your work on this issue is done, and this issue can be closed. I will confer with my colleague and the guys at Mobbr who should actually do this.

**Pull request merged**
